# To enable auto-completion and validation for this file in VSCode, install the RedHat YAML extension
# https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-transact-py/main/dbos/dbos-config.schema.json

name: fb_developer
language: python
runtimeConfig:
  start:
    - pip install -r requirements.txt
    - pip install dbos  # Ensure DBOS CLI is installed
    - python main.py
database:
  migrate:
    - alembic upgrade head
telemetry:
  logs:
    logLevel: INFO