"""v_01 init

Revision ID: 3ee757d9bebc
Revises: 
Create Date: 2025-02-18 12:32:36.669968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ee757d9bebc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_creatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authorization_category', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('call_to_action_type', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('object_story_id', sa.String(), nullable=True),
    sa.Column('object_story_spec', sa.JSON(), nullable=True),
    sa.Column('object_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_creatives_id'), 'ad_creatives', ['id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('bid_strategy', sa.String(), nullable=True),
    sa.Column('budget_schedule_specs', sa.String(), nullable=True),
    sa.Column('buying_type', sa.String(), nullable=True),
    sa.Column('daily_budget', sa.Integer(), nullable=True),
    sa.Column('lifetime_budget', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_skadnetwork_attribution', sa.Boolean(), nullable=True),
    sa.Column('objective', sa.String(), nullable=True),
    sa.Column('special_ad_categories', sa.JSON(), nullable=True),
    sa.Column('special_ad_category_country', sa.JSON(), nullable=True),
    sa.Column('spend_cap', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_table('ad_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('bid_amount', sa.Integer(), nullable=True),
    sa.Column('bid_strategy', sa.String(), nullable=True),
    sa.Column('billing_event', sa.String(), nullable=True),
    sa.Column('budget_schedule_specs', sa.JSON(), nullable=True),
    sa.Column('daily_budget', sa.Integer(), nullable=True),
    sa.Column('daily_min_spend_target', sa.Integer(), nullable=True),
    sa.Column('daily_spend_cap', sa.Integer(), nullable=True),
    sa.Column('destination_type', sa.String(), nullable=True),
    sa.Column('lifetime_budget', sa.Integer(), nullable=True),
    sa.Column('lifetime_min_spend_target', sa.Integer(), nullable=True),
    sa.Column('lifetime_spend_cap', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('optimization_goal', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('targeting', sa.JSON(), nullable=True),
    sa.Column('tune_for_category', sa.String(), nullable=True),
    sa.Column('time_start', sa.DateTime(), nullable=True),
    sa.Column('time_stop', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_sets_id'), 'ad_sets', ['id'], unique=False)
    op.create_table('ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_schedule_end_time', sa.DateTime(), nullable=True),
    sa.Column('ad_schedule_start_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ad_set_id', sa.Integer(), nullable=False),
    sa.Column('creative_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ad_set_id'], ['ad_sets.id'], ),
    sa.ForeignKeyConstraint(['creative_id'], ['ad_creatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ads_id'), 'ads', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ads_id'), table_name='ads')
    op.drop_table('ads')
    op.drop_index(op.f('ix_ad_sets_id'), table_name='ad_sets')
    op.drop_table('ad_sets')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_ad_creatives_id'), table_name='ad_creatives')
    op.drop_table('ad_creatives')
    # ### end Alembic commands ###
